name: iko_reliability_flutter
description: IKO Reliability Tool

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.1

environment:
    sdk: '>=3.0.0 <=4.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    auto_route: ^7.8.3
    http: ^1.1.0
    dropdown_search: ^5.0.1
    pluto_grid:
        git: https://github.com/jonathanmajh/pluto_grid
    file_picker: ^6.1.1
    spreadsheet_decoder: ^2.0.2
    hive_flutter: ^1.1.0
    hive: ^2.2.3
    csv: ^5.0.2
    provider: ^6.0.5
    drift: ^2.11.1
    sqlite3_flutter_libs: ^0.5.16
    path_provider: ^2.1.1
    path: ^1.8.3
    package_info_plus: ^5.0.1
    url_launcher: ^6.2.1
    flutter_window_close: ^0.2.2
    window_size:
        git:
            url: https://github.com/google/flutter-desktop-embedding
            path: plugins/window_size
    loading_animation_widget: ^1.2.0+4
    intl: ^0.18.1
    file_selector: ^1.0.1
    collection: ^1.17.2
    logger: ^2.0.2+1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1
    auto_route_generator: ^7.3.0
    hive_generator: ^2.0.0
    drift_dev: ^2.15.0
    build_runner: ^2.2.0
    squirrel:
        git: https://github.com/jonathanmajh/squirrel-flutter


flutter:
    uses-material-design: true
    fonts:
      - family: RobotoMono
        fonts:
          - asset: fonts/RobotoMono-Regular.ttf

squirrel:
  windows:
    appIcon: iko_logo.ico
    appFriendlyName: IKO Reliability PM Tool
    appDescription: IKO Reliability PM Tool
    authors: Jonathan
    loadingGif: iko_logo.gif
    # uninstallIconPngUrl: iko_logo.png
    releaseDirectory: releases
    # releaseUrl: https://jonathanmajh-iko-reliability-flutter.onrender.com